### ISSUE TITLE
Mời các bạn vào góp ý đồ án của nhóm mình

### ISSUE THREAD

**Issue by vlozg** [vlozg/DoAn_CuoiKy_DataScience#1]
Nhóm mình hiện tại đã hoàn thành code.
Tuy nhiên hiện tại chỉ mới có kết quả thử nghiệm trên 5% dữ liệu, chưa thể chạy được trên toàn bộ tập dữ liệu cũng như chưa báo cáo kỹ được phần modeling.

**Comment by littlefolkcs** [comment]
Sau khi nhóm thảo luận với nhau, bọn mình xin đưa ra một số góp ý với đồ án của nhóm các bạn như sau:
- Các bạn nên chỉnh sửa lại cấu trúc file của project vì bọn mình cảm thấy các bạn trình bày các cấu trúc file chưa được rõ ràng và cụ thể lắm.
- File readme các bạn nên giới thiệu chung về project, còn quá trình thực hiện đồ án các bạn có thể viết trong file Teamwork.
- Ở một số file notebook, các bạn nên xóa bớt các dòng pip install và các dòng in ra màn hình thông báo vì mình thấy nó rất dài.
- Các bạn có thể thêm một vài biểu đồ để visualize tập dữ liệu.
Trên đây là một số góp ý của nhóm mình, ngoài ra, ý tưởng project của các bạn rất hay và quá trình thu thập và parse html để lấy dữ liệu của các bạn rất kì công và sáng tạo. Good luck!

**Comment by vlozg** [comment]
Cảm ơn lời góp ý chi tiết cũng như lời khen của nhóm bạn dành cho nhóm mình.
Mong nhóm bạn cũng hoàn thành tốt đồ án kỳ này.
(｡･∀･)ﾉﾞ
